### ISSUE TITLE
Output is cut in PS 5.1

### ISSUE THREAD

**Issue by komsorg** [ryan-jan/MSCatalog#5]
Output is cut if executing Get-MSCatalogUpdate in PowerShell 5.1 running on Windows Server 2008 R2.
Saved output by using "< %PathToOutputfile.txt%" after cmdlet is the same.
![Cut output](https://user-images.githubusercontent.com/33907047/83350323-142fc500-a344-11ea-9ea8-f6162f88fa90.jpg)

**Comment by ryan-jan** [comment]
I believe this is just the default way that PS 5.1 formats the table given that the `Title` field contains some long values. For example if you use the following does it improve?

`Get-MSCatalogUpdate -Search 'asmedia' -AllPages | Format-Table -AutoSize`

Failing that you could use `Format-List` instead.

`Get-MSCatalogUpdate -Search 'asmedia' -AllPages | Format-List`

**Comment by komsorg** [comment]
`Format-List` parameter allows to fully display all property values, but it's output format is not handy for further data processing.
![image](https://user-images.githubusercontent.com/33907047/83519165-306a6800-a4e4-11ea-94ad-401ae76842dc.png)

Manually extended screen buffer width size in PS Console window settings.
![image](https://user-images.githubusercontent.com/33907047/83516394-a4eed800-a4df-11ea-95e8-f901562c5c9a.png)

When I tried to use proposed `Format-Table -AutoSize` option without hardcoding properties I got only Title, Products, Classification, LastUpdated, Size columns (Guid and other were absent) in output.

Finally I hardcoded properties, so the following command helped to archive the desired result: 
`Get-MSCatalogUpdate -Search "asmedia" -AllPages | Format-Table -AutoSize -Property Title, Products, Classification, Lastupdated, Version, Size, Guid`
![image](https://user-images.githubusercontent.com/33907047/83522700-b937d280-a4e9-11ea-843b-3f0f89c0d005.png)
![image](https://user-images.githubusercontent.com/33907047/83522743-c5239480-a4e9-11ea-8794-6fcdd1f3862e.png)

@ryan-jan Would you mind adding special parameter for exporting parsed data to .csv/.json file?

**Comment by ryan-jan** [comment]
I think you are misunderstanding the issue here. The `Get-MSCatalogUpdate` command simply returns the updates as a list of PSCustomObjects. The display is handled by PowerShell's built in [formatting engine](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-7). The only reason the table is not displaying very nicely is because the title field contains very long names. For example, if I make my PowerShell console window really narrow and run the `Get-Process` command, you can see that long process names are replaced with `...` as they fall off the screen width. This is normal behaviour.

![Annotation 2020-06-02 171840](https://user-images.githubusercontent.com/40335656/83544042-36b51000-a4f5-11ea-814a-1c8fb1aaa61e.png)

If you want to store the output as CSV or JSON you can do it already using PowerShell native commands. For example:

```powershell
Get-MSCatalogUpdate -Search 'asmedia' | Export-Csv -Path .\test.csv -NoClobber -NoTypeInformation
```
or
```powershell
Get-MSCatalogUpdate -Search 'asmedia' | ConvertTo-Json | Set-Content -Path .\test.json
```
